version: '3.8'

services:




  app:
    build:
      context: .
      target: dev-stage
      
    ports:
      - "8080:8080"
      - "40000:40000" 

    volumes:
      - .:/app 

    security_opt:
      - "seccomp:unconfined"
    command: >
      sh -c "go install github.com/go-delve/delve/cmd/dlv@latest &&
                                      dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec ./cmd"