services:
  app0:
    build:
      context: .
      target: dev-stage
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - .:/app
    security_opt:
      - "seccomp:unconfined"
    command: >
      sh -c "go build -o /app/main ./cmd &&
             /go/bin/dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec /app/main"
